/**
 * Product photo galleries. GENERATED by scripts/import-photos.mts — do not edit by hand.
 * The first entry is always the main product image.
 */
export const gallery: Record<string, string[]> = {
  "metallic-premium-white-board": [
    "/images/products/metallic-premium-white-board.webp?v=a3c71e8c3a",
    "/images/products/metallic-premium-white-board/1.webp?v=ae50fda028",
    "/images/products/metallic-premium-white-board/2.webp?v=1527d3b18e",
    "/images/products/metallic-premium-white-board/3.webp?v=00651b78cf",
    "/images/products/metallic-premium-white-board/4.webp?v=cc8f8f476f",
    "/images/products/metallic-premium-white-board/5.webp?v=f42ff69b85",
    "/images/products/metallic-premium-white-board/6.webp?v=c33d930bf1",
    "/images/products/metallic-premium-white-board/7.webp?v=7ab5ad74c4",
  ],
  "eco-premium-white-board": [
    "/images/products/eco-premium-white-board.webp?v=47a56818c1",
    "/images/products/eco-premium-white-board/1.webp?v=4c07e469d5",
    "/images/products/eco-premium-white-board/2.webp?v=95d994efba",
    "/images/products/eco-premium-white-board/3.webp?v=dfcb70f064",
    "/images/products/eco-premium-white-board/4.webp?v=01a91c3ba9",
    "/images/products/eco-premium-white-board/5.webp?v=23f0ddb0d8",
    "/images/products/eco-premium-white-board/6.webp?v=959ccb611a",
  ],
  "deluxe-standard-white-board": [
    "/images/products/deluxe-standard-white-board.webp?v=7cea1872b2",
  ],
  "eco-regular-white-board": [
    "/images/products/eco-regular-white-board.webp?v=92b7960c51",
  ],
  "metallic-premium-chalk-board": [
    "/images/products/metallic-premium-chalk-board.webp?v=0bdb41a5a0",
    "/images/products/metallic-premium-chalk-board/1.webp?v=ac8978c709",
    "/images/products/metallic-premium-chalk-board/2.webp?v=d469e09e0b",
    "/images/products/metallic-premium-chalk-board/3.webp?v=35c97c25f4",
    "/images/products/metallic-premium-chalk-board/4.webp?v=44869f03e3",
    "/images/products/metallic-premium-chalk-board/5.webp?v=cf968b490c",
    "/images/products/metallic-premium-chalk-board/6.webp?v=bf77a8741b",
    "/images/products/metallic-premium-chalk-board/7.webp?v=e5e86cfb0c",
  ],
  "eco-premium-chalk-board": [
    "/images/products/eco-premium-chalk-board.webp?v=dba002df92",
    "/images/products/eco-premium-chalk-board/1.webp?v=2688000cdc",
    "/images/products/eco-premium-chalk-board/2.webp?v=05aceab4a8",
    "/images/products/eco-premium-chalk-board/3.webp?v=0f50b9435c",
    "/images/products/eco-premium-chalk-board/4.webp?v=8a0d03c4f7",
    "/images/products/eco-premium-chalk-board/5.webp?v=dd5ec2e5a6",
    "/images/products/eco-premium-chalk-board/6.webp?v=627ba42dfd",
  ],
  "deluxe-standard-chalk-board": [
    "/images/products/deluxe-standard-chalk-board.webp?v=9e4056cf99",
  ],
  "metallic-premium-notice-board": [
    "/images/products/metallic-premium-notice-board.webp?v=2580051b3a",
    "/images/products/metallic-premium-notice-board/1.webp?v=659480ac16",
    "/images/products/metallic-premium-notice-board/2.webp?v=2de31fb1b3",
    "/images/products/metallic-premium-notice-board/3.webp?v=5c2c453c1e",
    "/images/products/metallic-premium-notice-board/4.webp?v=c54559f75a",
    "/images/products/metallic-premium-notice-board/5.webp?v=09cfd407a2",
    "/images/products/metallic-premium-notice-board/6.webp?v=1725633549",
    "/images/products/metallic-premium-notice-board/7.webp?v=3178ceee26",
    "/images/products/metallic-premium-notice-board/8.webp?v=5990cacd80",
    "/images/products/metallic-premium-notice-board/9.webp?v=036fb1fa51",
    "/images/products/metallic-premium-notice-board/10.webp?v=be5445bdb9",
    "/images/products/metallic-premium-notice-board/11.webp?v=878607f9b0",
    "/images/products/metallic-premium-notice-board/12.webp?v=ad04687dfc",
  ],
  "eco-premium-notice-board": [
    "/images/products/eco-premium-notice-board.webp?v=7c83896bae",
    "/images/products/eco-premium-notice-board/1.webp?v=7e03298ded",
    "/images/products/eco-premium-notice-board/2.webp?v=338e0122b0",
    "/images/products/eco-premium-notice-board/3.webp?v=304def2c90",
    "/images/products/eco-premium-notice-board/4.webp?v=c7ff36d3e7",
    "/images/products/eco-premium-notice-board/5.webp?v=7d7a50b4c9",
    "/images/products/eco-premium-notice-board/6.webp?v=30ce04ced6",
    "/images/products/eco-premium-notice-board/7.webp?v=89c099a11c",
    "/images/products/eco-premium-notice-board/8.webp?v=eb51d2b948",
  ],
  "deluxe-standard-notice-board": [
    "/images/products/deluxe-standard-notice-board.webp?v=f34900f7f5",
  ],
  "eco-regular-notice-board": [
    "/images/products/eco-regular-notice-board.webp?v=bd2cb345e9",
  ],
  "metallic-premium-magnetic-board": [
    "/images/products/metallic-premium-magnetic-board.webp?v=3ecdcbf72d",
    "/images/products/metallic-premium-magnetic-board/1.webp?v=6a61b241b7",
    "/images/products/metallic-premium-magnetic-board/2.webp?v=f57cf1284b",
    "/images/products/metallic-premium-magnetic-board/3.webp?v=8b303cc898",
    "/images/products/metallic-premium-magnetic-board/4.webp?v=0fbd3afe52",
    "/images/products/metallic-premium-magnetic-board/5.webp?v=f42ff69b85",
    "/images/products/metallic-premium-magnetic-board/6.webp?v=cffb3acbfc",
    "/images/products/metallic-premium-magnetic-board/7.webp?v=af1a22eaad",
    "/images/products/metallic-premium-magnetic-board/8.webp?v=50759014d3",
  ],
  "deluxe-standard-magnetic-board": [
    "/images/products/deluxe-standard-magnetic-board.webp?v=57b2f9134c",
  ],
  "eco-regular-magnetic-board": [
    "/images/products/eco-regular-magnetic-board.webp?v=4162c413eb",
  ],
  "metallic-premium-ceramic-board": [
    "/images/products/metallic-premium-ceramic-board.webp?v=05639f1c8e",
    "/images/products/metallic-premium-ceramic-board/1.webp?v=a5f13b7f40",
    "/images/products/metallic-premium-ceramic-board/2.webp?v=0af934ab77",
    "/images/products/metallic-premium-ceramic-board/3.webp?v=dfcc824de6",
    "/images/products/metallic-premium-ceramic-board/4.webp?v=c45d20fa7e",
    "/images/products/metallic-premium-ceramic-board/5.webp?v=ffb4cb682c",
    "/images/products/metallic-premium-ceramic-board/6.webp?v=a7e7f319c3",
    "/images/products/metallic-premium-ceramic-board/7.webp?v=15e873bae5",
    "/images/products/metallic-premium-ceramic-board/8.webp?v=2da58d9d29",
  ],
  "deluxe-standard-ceramic-board": [
    "/images/products/deluxe-standard-ceramic-board.webp?v=3e9c2e78ef",
  ],
  "acrylic-folder-display-board": [
    "/images/products/acrylic-folder-display-board.webp?v=8916658323",
  ],
  "cork-notice-board": [
    "/images/products/cork-notice-board.webp?v=0d1c8cb0a4",
  ],
  "combination-board": [
    "/images/products/combination-board.webp?v=9a21d3d620",
  ],
  "fabric-notice-board": [
    "/images/products/fabric-notice-board.webp?v=a89b44b8c3",
  ],
  "deluxe-45mm-adc-notice-board-double-door": [
    "/images/products/deluxe-45mm-adc-notice-board-double-door.webp?v=4cc37c0f02",
  ],
  "deluxe-45mm-adc-notice-board-single-door": [
    "/images/products/deluxe-45mm-adc-notice-board-single-door.webp?v=12b342f4e3",
  ],
  "eco-adc-notice-board-single-door": [
    "/images/products/eco-adc-notice-board-single-door.webp?v=65361d00f4",
  ],
  "four-line-square-line-practice-board": [
    "/images/products/four-line-square-line-practice-board.webp?v=7c6e6fdeb0",
  ],
  "key-hanger-board": [
    "/images/products/key-hanger-board.webp?v=34569be30e",
  ],
  "student-study-table": [
    "/images/products/student-study-table.webp?v=d2e6a8b2ee",
  ],
  "grooved-boards": [
    "/images/products/grooved-boards.webp?v=fc8e8cb02a",
    "/images/products/grooved-boards/1.webp?v=1831eee95a",
  ],
  "perforated-board": [
    "/images/products/perforated-board.webp?v=3bb4cea365",
  ],
  "three-leg-stand": [
    "/images/products/three-leg-stand.webp?v=93cb3be846",
  ],
  "four-leg-stand": [
    "/images/products/four-leg-stand.webp?v=a0c937a058",
  ],
  "telescopic-stand": [
    "/images/products/telescopic-stand.webp?v=f71fbba413",
  ],
  "newspaper-stand": [
    "/images/products/newspaper-stand.webp?v=ff5cabaa3c",
    "/images/products/newspaper-stand/1.webp?v=2ce8a7e8e5",
  ],
  "revolving-stand": [
    "/images/products/revolving-stand.webp?v=73ac420c0c",
  ],
  "zig-zag-stand": [
    "/images/products/zig-zag-stand.webp?v=58df28c614",
  ],
  "magazine-stand": [
    "/images/products/magazine-stand.webp?v=92757366b2",
  ],
  "first-aid-box": [
    "/images/products/first-aid-box.webp?v=6c9d4fa849",
  ],
  "letter-box": [
    "/images/products/letter-box.webp?v=f5af0a743a",
  ],
  "file-rack": [
    "/images/products/file-rack.webp?v=03e15969cd",
  ],
  "graphic-mdf-base-clipboard": [
    "/images/products/graphic-mdf-base-clipboard.webp?v=3845d427da",
    "/images/products/graphic-mdf-base-clipboard/1.webp?v=5284440d96",
    "/images/products/graphic-mdf-base-clipboard/2.webp?v=ea222462b9",
    "/images/products/graphic-mdf-base-clipboard/3.webp?v=0cd91b5db5",
    "/images/products/graphic-mdf-base-clipboard/4.webp?v=b29d5087f8",
  ],
  "laminate-mdf-base-clipboard": [
    "/images/products/laminate-mdf-base-clipboard.webp?v=a48f1c6fda",
    "/images/products/laminate-mdf-base-clipboard/1.webp?v=41cb8ea7a6",
  ],
  "pre-lam-mdf-base-clipboard": [
    "/images/products/pre-lam-mdf-base-clipboard.webp?v=c572377f72",
    "/images/products/pre-lam-mdf-base-clipboard/1.webp?v=498c31019f",
    "/images/products/pre-lam-mdf-base-clipboard/2.webp?v=66b3990162",
    "/images/products/pre-lam-mdf-base-clipboard/3.webp?v=2facce3064",
    "/images/products/pre-lam-mdf-base-clipboard/4.webp?v=6307000e03",
  ],
  "crystal-clear-base-clipboard": [
    "/images/products/crystal-clear-base-clipboard.webp?v=d347d02577",
  ],
  "crystal-colour-base-clipboard": [
    "/images/products/crystal-colour-base-clipboard.webp?v=566c0fee87",
  ],
  "pds-sb-807": [
    "/images/products/pds-sb-807.webp?v=c7f1f1fea9",
  ],
  "pds-sb-810": [
    "/images/products/pds-sb-810.webp?v=9d21f6fd25",
  ],
  "pds-sb-804": [
    "/images/products/pds-sb-804.webp?v=e253cec996",
  ],
  "pds-sb-812": [
    "/images/products/pds-sb-812.webp?v=ffe9b1233b",
  ],
  "pds-sb-801": [
    "/images/products/pds-sb-801.webp?v=fedfc43c0a",
  ],
  "pds-sb-802": [
    "/images/products/pds-sb-802.webp?v=19decf5377",
  ],
  "pds-sb-803": [
    "/images/products/pds-sb-803.webp?v=1ecb75cba9",
  ],
  "pds-sb-805": [
    "/images/products/pds-sb-805.webp?v=9d1f339eee",
  ],
  "pds-sb-806": [
    "/images/products/pds-sb-806.webp?v=713346de9d",
  ],
  "pds-sb-808": [
    "/images/products/pds-sb-808.webp?v=97fe1e3bfc",
  ],
  "pds-sb-809": [
    "/images/products/pds-sb-809.webp?v=a4e3140c3d",
  ],
  "pds-sb-811": [
    "/images/products/pds-sb-811.webp?v=9042549180",
  ],
  "pds-sb-813": [
    "/images/products/pds-sb-813.webp?v=b5576a4aa3",
  ],
  "pds-sb-814": [
    "/images/products/pds-sb-814.webp?v=fcd4906d15",
  ],
  "pds-sb-815": [
    "/images/products/pds-sb-815.webp?v=a173f5f0a2",
  ],
  "dry-wipe-schedule-board": [
    "/images/products/dry-wipe-schedule-board.webp?v=ed0288e299",
  ],
};
