/**
 * Product photo galleries. GENERATED by scripts/import-photos.mts — do not edit by hand.
 * The first entry is always the main product image.
 */
export const gallery: Record<string, string[]> = {
  "metallic-premium-white-board": [
    "/images/products/metallic-premium-white-board.webp?v=a3c71e8c3a",
    "/images/products/metallic-premium-white-board/1.webp?v=c264674bcf",
    "/images/products/metallic-premium-white-board/2.webp?v=c37ad3523c",
    "/images/products/metallic-premium-white-board/3.webp?v=841dc9097b",
    "/images/products/metallic-premium-white-board/4.webp?v=83ae62d649",
    "/images/products/metallic-premium-white-board/5.webp?v=17431d5493",
    "/images/products/metallic-premium-white-board/6.webp?v=f47adf46fc",
  ],
  "eco-premium-white-board": [
    "/images/products/eco-premium-white-board.webp?v=47a56818c1",
    "/images/products/eco-premium-white-board/1.webp?v=8f0716cef0",
    "/images/products/eco-premium-white-board/2.webp?v=c6fc91f7ea",
    "/images/products/eco-premium-white-board/3.webp?v=49ce778b31",
    "/images/products/eco-premium-white-board/4.webp?v=851d672fed",
    "/images/products/eco-premium-white-board/5.webp?v=a185421b8d",
    "/images/products/eco-premium-white-board/6.webp?v=ecdf69e52f",
  ],
  "eco-premium-both-side-board": [
    "/images/products/eco-premium-both-side-board.webp?v=39dff3ded5",
    "/images/products/eco-premium-both-side-board/1.webp?v=33ab5636aa",
    "/images/products/eco-premium-both-side-board/2.webp?v=183fd33f43",
    "/images/products/eco-premium-both-side-board/3.webp?v=df375e2a3a",
    "/images/products/eco-premium-both-side-board/4.webp?v=96ae2564ae",
    "/images/products/eco-premium-both-side-board/5.webp?v=3c7cae6ec1",
    "/images/products/eco-premium-both-side-board/6.webp?v=80b2a4b756",
  ],
  "deluxe-standard-white-board": [
    "/images/products/deluxe-standard-white-board.webp?v=7cea1872b2",
  ],
  "eco-regular-white-board": [
    "/images/products/eco-regular-white-board.webp?v=92b7960c51",
  ],
  "metallic-premium-chalk-board": [
    "/images/products/metallic-premium-chalk-board.webp?v=0bdb41a5a0",
    "/images/products/metallic-premium-chalk-board/1.webp?v=15b17d6768",
    "/images/products/metallic-premium-chalk-board/2.webp?v=5dc8ef5698",
    "/images/products/metallic-premium-chalk-board/3.webp?v=a3d8fc6fac",
    "/images/products/metallic-premium-chalk-board/4.webp?v=a92193d116",
    "/images/products/metallic-premium-chalk-board/5.webp?v=ba7b3fc190",
    "/images/products/metallic-premium-chalk-board/6.webp?v=4f64ead1cd",
  ],
  "eco-premium-chalk-board": [
    "/images/products/eco-premium-chalk-board.webp?v=dba002df92",
    "/images/products/eco-premium-chalk-board/1.webp?v=4835ff9fa2",
    "/images/products/eco-premium-chalk-board/2.webp?v=7cea15610b",
    "/images/products/eco-premium-chalk-board/3.webp?v=13fa698375",
    "/images/products/eco-premium-chalk-board/4.webp?v=d7ac1d0cf6",
    "/images/products/eco-premium-chalk-board/5.webp?v=fd32f223a9",
    "/images/products/eco-premium-chalk-board/6.webp?v=e1dddb6725",
  ],
  "deluxe-standard-chalk-board": [
    "/images/products/deluxe-standard-chalk-board.webp?v=9e4056cf99",
  ],
  "metallic-premium-notice-board": [
    "/images/products/metallic-premium-notice-board.webp?v=2580051b3a",
    "/images/products/metallic-premium-notice-board/1.webp?v=63eb429f91",
    "/images/products/metallic-premium-notice-board/2.webp?v=1e631e1c6c",
    "/images/products/metallic-premium-notice-board/3.webp?v=683df3146f",
    "/images/products/metallic-premium-notice-board/4.webp?v=a841d7eb2e",
    "/images/products/metallic-premium-notice-board/5.webp?v=fe87c64cb9",
    "/images/products/metallic-premium-notice-board/6.webp?v=3996eae1df",
    "/images/products/metallic-premium-notice-board/7.webp?v=d744b7c1ce",
    "/images/products/metallic-premium-notice-board/8.webp?v=1d67dba4c8",
    "/images/products/metallic-premium-notice-board/9.webp?v=27962af2bc",
    "/images/products/metallic-premium-notice-board/10.webp?v=0f5afd8291",
    "/images/products/metallic-premium-notice-board/11.webp?v=c548f078eb",
  ],
  "eco-premium-notice-board": [
    "/images/products/eco-premium-notice-board.webp?v=7c83896bae",
    "/images/products/eco-premium-notice-board/1.webp?v=d048443b76",
    "/images/products/eco-premium-notice-board/2.webp?v=03911b7c1c",
    "/images/products/eco-premium-notice-board/3.webp?v=261061dafb",
    "/images/products/eco-premium-notice-board/4.webp?v=b612a33620",
    "/images/products/eco-premium-notice-board/5.webp?v=13c9a645d9",
    "/images/products/eco-premium-notice-board/6.webp?v=0de66686b9",
    "/images/products/eco-premium-notice-board/7.webp?v=b89b739316",
    "/images/products/eco-premium-notice-board/8.webp?v=a486755ca5",
  ],
  "deluxe-standard-notice-board": [
    "/images/products/deluxe-standard-notice-board.webp?v=f34900f7f5",
  ],
  "eco-regular-notice-board": [
    "/images/products/eco-regular-notice-board.webp?v=bd2cb345e9",
  ],
  "metallic-premium-magnetic-board": [
    "/images/products/metallic-premium-magnetic-board.webp?v=3ecdcbf72d",
    "/images/products/metallic-premium-magnetic-board/1.webp?v=1681d5eafa",
    "/images/products/metallic-premium-magnetic-board/2.webp?v=dcd5e5088d",
    "/images/products/metallic-premium-magnetic-board/3.webp?v=16efc382b4",
    "/images/products/metallic-premium-magnetic-board/4.webp?v=6572dd6962",
    "/images/products/metallic-premium-magnetic-board/5.webp?v=17431d5493",
    "/images/products/metallic-premium-magnetic-board/6.webp?v=908fa8e7e4",
    "/images/products/metallic-premium-magnetic-board/7.webp?v=ff0a8a08e6",
    "/images/products/metallic-premium-magnetic-board/8.webp?v=a9e4099982",
    "/images/products/metallic-premium-magnetic-board/9.webp?v=22942000fa",
    "/images/products/metallic-premium-magnetic-board/10.webp?v=9ec7efe62b",
  ],
  "deluxe-standard-magnetic-board": [
    "/images/products/deluxe-standard-magnetic-board.webp?v=57b2f9134c",
  ],
  "eco-regular-magnetic-board": [
    "/images/products/eco-regular-magnetic-board.webp?v=15037b0795",
    "/images/products/eco-regular-magnetic-board/1.webp?v=29d3ca5e92",
    "/images/products/eco-regular-magnetic-board/2.webp?v=0d2c2a5de8",
    "/images/products/eco-regular-magnetic-board/3.webp?v=a7b8ceaea1",
    "/images/products/eco-regular-magnetic-board/4.webp?v=851d672fed",
    "/images/products/eco-regular-magnetic-board/5.webp?v=18932b1443",
    "/images/products/eco-regular-magnetic-board/6.webp?v=34b9bd2e36",
    "/images/products/eco-regular-magnetic-board/7.webp?v=d29afccddf",
    "/images/products/eco-regular-magnetic-board/8.webp?v=b2a598a683",
    "/images/products/eco-regular-magnetic-board/9.webp?v=dbcb03a030",
    "/images/products/eco-regular-magnetic-board/10.webp?v=c7c835da7a",
  ],
  "metallic-premium-ceramic-board": [
    "/images/products/metallic-premium-ceramic-board.webp?v=05639f1c8e",
    "/images/products/metallic-premium-ceramic-board/1.webp?v=5f6e174a80",
    "/images/products/metallic-premium-ceramic-board/2.webp?v=42cf0c190a",
    "/images/products/metallic-premium-ceramic-board/3.webp?v=ba6b886620",
    "/images/products/metallic-premium-ceramic-board/4.webp?v=2873d8ead1",
    "/images/products/metallic-premium-ceramic-board/5.webp?v=15066570cf",
    "/images/products/metallic-premium-ceramic-board/6.webp?v=524542d576",
    "/images/products/metallic-premium-ceramic-board/7.webp?v=9b51cd113f",
    "/images/products/metallic-premium-ceramic-board/8.webp?v=9d8edcdfea",
    "/images/products/metallic-premium-ceramic-board/9.webp?v=a81a05e741",
    "/images/products/metallic-premium-ceramic-board/10.webp?v=df5c01b158",
  ],
  "deluxe-standard-ceramic-board": [
    "/images/products/deluxe-standard-ceramic-board.webp?v=3e9c2e78ef",
  ],
  "acrylic-folder-display-board": [
    "/images/products/acrylic-folder-display-board.webp?v=8916658323",
  ],
  "cork-notice-board": [
    "/images/products/cork-notice-board.webp?v=0d1c8cb0a4",
  ],
  "combination-board": [
    "/images/products/combination-board.webp?v=9a21d3d620",
  ],
  "fabric-notice-board": [
    "/images/products/fabric-notice-board.webp?v=a89b44b8c3",
  ],
  "deluxe-45mm-adc-notice-board-double-door": [
    "/images/products/deluxe-45mm-adc-notice-board-double-door.webp?v=4cc37c0f02",
  ],
  "deluxe-45mm-adc-notice-board-single-door": [
    "/images/products/deluxe-45mm-adc-notice-board-single-door.webp?v=12b342f4e3",
  ],
  "eco-adc-notice-board-single-door": [
    "/images/products/eco-adc-notice-board-single-door.webp?v=65361d00f4",
  ],
  "four-line-square-line-practice-board": [
    "/images/products/four-line-square-line-practice-board.webp?v=7c6e6fdeb0",
  ],
  "key-hanger-board": [
    "/images/products/key-hanger-board.webp?v=34569be30e",
  ],
  "student-study-table": [
    "/images/products/student-study-table.webp?v=cb6f6ab92c",
    "/images/products/student-study-table/1.webp?v=c8e4800012",
    "/images/products/student-study-table/2.webp?v=a9b21d84e1",
    "/images/products/student-study-table/3.webp?v=5826c0a363",
    "/images/products/student-study-table/4.webp?v=f7c470967d",
    "/images/products/student-study-table/5.webp?v=aa6b6c6ea4",
    "/images/products/student-study-table/6.webp?v=c5145f913b",
    "/images/products/student-study-table/7.webp?v=cbcd6acf82",
    "/images/products/student-study-table/8.webp?v=d010f7f383",
    "/images/products/student-study-table/9.webp?v=779c035d79",
    "/images/products/student-study-table/10.webp?v=11d3e18a13",
    "/images/products/student-study-table/11.webp?v=01f5c1dd02",
    "/images/products/student-study-table/12.webp?v=1ad0050fde",
  ],
  "grooved-boards": [
    "/images/products/grooved-boards.webp?v=fc8e8cb02a",
    "/images/products/grooved-boards/1.webp?v=1831eee95a",
  ],
  "perforated-board": [
    "/images/products/perforated-board.webp?v=3bb4cea365",
  ],
  "three-leg-stand": [
    "/images/products/three-leg-stand.webp?v=93cb3be846",
  ],
  "four-leg-stand": [
    "/images/products/four-leg-stand.webp?v=a0c937a058",
  ],
  "telescopic-stand": [
    "/images/products/telescopic-stand.webp?v=f71fbba413",
  ],
  "newspaper-stand": [
    "/images/products/newspaper-stand.webp?v=ff5cabaa3c",
    "/images/products/newspaper-stand/1.webp?v=2ce8a7e8e5",
  ],
  "revolving-stand": [
    "/images/products/revolving-stand.webp?v=73ac420c0c",
  ],
  "zig-zag-stand": [
    "/images/products/zig-zag-stand.webp?v=58df28c614",
  ],
  "magazine-stand": [
    "/images/products/magazine-stand.webp?v=92757366b2",
  ],
  "first-aid-box": [
    "/images/products/first-aid-box.webp?v=6c9d4fa849",
  ],
  "letter-box": [
    "/images/products/letter-box.webp?v=f5af0a743a",
  ],
  "file-rack": [
    "/images/products/file-rack.webp?v=03e15969cd",
  ],
  "graphic-mdf-base-clipboard": [
    "/images/products/graphic-mdf-base-clipboard.webp?v=3845d427da",
    "/images/products/graphic-mdf-base-clipboard/1.webp?v=5284440d96",
    "/images/products/graphic-mdf-base-clipboard/2.webp?v=ea222462b9",
    "/images/products/graphic-mdf-base-clipboard/3.webp?v=0cd91b5db5",
    "/images/products/graphic-mdf-base-clipboard/4.webp?v=b29d5087f8",
  ],
  "laminate-mdf-base-clipboard": [
    "/images/products/laminate-mdf-base-clipboard.webp?v=a48f1c6fda",
    "/images/products/laminate-mdf-base-clipboard/1.webp?v=41cb8ea7a6",
  ],
  "pre-lam-mdf-base-clipboard": [
    "/images/products/pre-lam-mdf-base-clipboard.webp?v=c572377f72",
    "/images/products/pre-lam-mdf-base-clipboard/1.webp?v=498c31019f",
    "/images/products/pre-lam-mdf-base-clipboard/2.webp?v=66b3990162",
    "/images/products/pre-lam-mdf-base-clipboard/3.webp?v=2facce3064",
    "/images/products/pre-lam-mdf-base-clipboard/4.webp?v=6307000e03",
  ],
  "crystal-clear-base-clipboard": [
    "/images/products/crystal-clear-base-clipboard.webp?v=d347d02577",
  ],
  "crystal-colour-base-clipboard": [
    "/images/products/crystal-colour-base-clipboard.webp?v=566c0fee87",
  ],
  "pds-sb-807": [
    "/images/products/pds-sb-807.webp?v=c7f1f1fea9",
  ],
  "pds-sb-810": [
    "/images/products/pds-sb-810.webp?v=9d21f6fd25",
  ],
  "pds-sb-804": [
    "/images/products/pds-sb-804.webp?v=e253cec996",
  ],
  "pds-sb-812": [
    "/images/products/pds-sb-812.webp?v=ffe9b1233b",
  ],
  "pds-sb-801": [
    "/images/products/pds-sb-801.webp?v=fedfc43c0a",
  ],
  "pds-sb-802": [
    "/images/products/pds-sb-802.webp?v=19decf5377",
  ],
  "pds-sb-803": [
    "/images/products/pds-sb-803.webp?v=1ecb75cba9",
  ],
  "pds-sb-805": [
    "/images/products/pds-sb-805.webp?v=9d1f339eee",
  ],
  "pds-sb-806": [
    "/images/products/pds-sb-806.webp?v=713346de9d",
  ],
  "pds-sb-808": [
    "/images/products/pds-sb-808.webp?v=97fe1e3bfc",
  ],
  "pds-sb-809": [
    "/images/products/pds-sb-809.webp?v=a4e3140c3d",
  ],
  "pds-sb-811": [
    "/images/products/pds-sb-811.webp?v=9042549180",
  ],
  "pds-sb-813": [
    "/images/products/pds-sb-813.webp?v=b5576a4aa3",
  ],
  "pds-sb-814": [
    "/images/products/pds-sb-814.webp?v=fcd4906d15",
  ],
  "pds-sb-815": [
    "/images/products/pds-sb-815.webp?v=a173f5f0a2",
  ],
  "dry-wipe-schedule-board": [
    "/images/products/dry-wipe-schedule-board.webp?v=ed0288e299",
  ],
};
