/**
 * Product photo galleries. GENERATED by scripts/import-photos.mts — do not edit by hand.
 * The first entry is always the main product image.
 */
export const gallery: Record<string, string[]> = {
  "metallic-premium-white-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/6",
  ],
  "eco-premium-white-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/6",
  ],
  "eco-premium-both-side-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/6",
  ],
  "deluxe-standard-white-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-standard-white-board",
  ],
  "eco-regular-white-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-white-board",
  ],
  "metallic-premium-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/6",
  ],
  "eco-premium-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/6",
  ],
  "deluxe-standard-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-standard-chalk-board",
  ],
  "eco-regular-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-chalk-board",
  ],
  "metallic-premium-magnetic-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-chalk-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-chalk-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-chalk-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-chalk-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-chalk-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-chalk-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-chalk-board/6",
  ],
  "deluxe-standard-magnetic-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-standard-magnetic-chalk-board",
  ],
  "eco-regular-magnetic-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-chalk-board",
  ],
  "metallic-premium-ceramic-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board",
  ],
  "deluxe-standard-ceramic-chalk-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-standard-chalk-board",
  ],
  "metallic-premium-notice-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/6",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/7",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/8",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/9",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/10",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/11",
  ],
  "eco-premium-notice-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/6",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/7",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/8",
  ],
  "deluxe-standard-notice-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-standard-notice-board",
  ],
  "eco-regular-notice-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-notice-board",
  ],
  "metallic-premium-magnetic-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/6",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/7",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/8",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/9",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/10",
  ],
  "deluxe-standard-magnetic-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-standard-magnetic-board",
  ],
  "eco-regular-magnetic-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/6",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/7",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/8",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/9",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/10",
  ],
  "metallic-premium-ceramic-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/6",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/7",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/8",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/9",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/10",
  ],
  "deluxe-standard-ceramic-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-standard-ceramic-board",
  ],
  "acrylic-folder-display-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/acrylic-folder-display-board",
  ],
  "cork-notice-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/cork-notice-board",
  ],
  "combination-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/combination-board",
  ],
  "fabric-notice-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/fabric-notice-board",
  ],
  "deluxe-45mm-adc-notice-board-double-door": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-45mm-adc-notice-board-double-door",
  ],
  "deluxe-45mm-adc-notice-board-single-door": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/deluxe-45mm-adc-notice-board-single-door",
  ],
  "eco-adc-notice-board-single-door": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-adc-notice-board-single-door",
  ],
  "four-line-square-line-practice-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/four-line-square-line-practice-board",
  ],
  "key-hanger-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/key-hanger-board",
  ],
  "student-study-table": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/4",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/5",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/6",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/7",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/8",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/9",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/10",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/11",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/student-study-table/12",
  ],
  "grooved-boards": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/grooved-boards",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/grooved-boards/1",
  ],
  "perforated-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/perforated-board",
  ],
  "three-leg-stand": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/three-leg-stand",
  ],
  "four-leg-stand": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/four-leg-stand",
  ],
  "telescopic-stand": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/telescopic-stand",
  ],
  "newspaper-stand": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/newspaper-stand",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/newspaper-stand/1",
  ],
  "revolving-stand": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/revolving-stand",
  ],
  "zig-zag-stand": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/zig-zag-stand",
  ],
  "magazine-stand": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/magazine-stand",
  ],
  "first-aid-box": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/first-aid-box",
  ],
  "letter-box": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/letter-box",
  ],
  "file-rack": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/file-rack",
  ],
  "graphic-mdf-base-clipboard": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/graphic-mdf-base-clipboard",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/graphic-mdf-base-clipboard/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/graphic-mdf-base-clipboard/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/graphic-mdf-base-clipboard/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/graphic-mdf-base-clipboard/4",
  ],
  "laminate-mdf-base-clipboard": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/laminate-mdf-base-clipboard",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/laminate-mdf-base-clipboard/1",
  ],
  "pre-lam-mdf-base-clipboard": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pre-lam-mdf-base-clipboard",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pre-lam-mdf-base-clipboard/1",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pre-lam-mdf-base-clipboard/2",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pre-lam-mdf-base-clipboard/3",
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pre-lam-mdf-base-clipboard/4",
  ],
  "crystal-clear-base-clipboard": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/crystal-clear-base-clipboard",
  ],
  "crystal-colour-base-clipboard": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/crystal-colour-base-clipboard",
  ],
  "pds-sb-807": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-807",
  ],
  "pds-sb-810": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-810",
  ],
  "pds-sb-804": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-804",
  ],
  "pds-sb-812": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-812",
  ],
  "pds-sb-801": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-801",
  ],
  "pds-sb-802": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-802",
  ],
  "pds-sb-803": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-803",
  ],
  "pds-sb-805": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-805",
  ],
  "pds-sb-806": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-806",
  ],
  "pds-sb-808": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-808",
  ],
  "pds-sb-809": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-809",
  ],
  "pds-sb-811": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-811",
  ],
  "pds-sb-813": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-813",
  ],
  "pds-sb-814": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-814",
  ],
  "pds-sb-815": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/pds-sb-815",
  ],
  "dry-wipe-schedule-board": [
    "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/dry-wipe-schedule-board",
  ],
};
