/**
 * Board sizes with a photo per size. GENERATED by scripts/import-photos.mts — do not edit by hand.
 * Source: per-size folders of the HQ listing photos (e.g. "ECO WB/2x3 Feet").
 */
export interface SizeOption {
  label: string;
  image: string;
}

export const sizeOptions: Record<string, SizeOption[]> = {
  "metallic-premium-white-board": [
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-white-board/size-3x4" },
  ],
  "metallic-premium-chalk-board": [
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-chalk-board/size-3x4" },
  ],
  "metallic-premium-notice-board": [
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-notice-board/size-3x4" },
  ],
  "metallic-premium-magnetic-board": [
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-magnetic-board/size-3x4" },
  ],
  "metallic-premium-ceramic-board": [
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/metallic-premium-ceramic-board/size-3x4" },
  ],
  "eco-premium-white-board": [
    { label: "1 × 1 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-1x1" },
    { label: "1 × 1.5 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-1x1.5" },
    { label: "1 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-1x2" },
    { label: "1.5 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-1.5x2" },
    { label: "1.5 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-1.5x3" },
    { label: "2 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-2x2" },
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-white-board/size-3x4" },
  ],
  "eco-premium-both-side-board": [
    { label: "1 × 1 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-1x1" },
    { label: "1 × 1.5 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-1x1.5" },
    { label: "1 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-1x2" },
    { label: "1.5 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-1.5x2" },
    { label: "1.5 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-1.5x3" },
    { label: "2 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-2x2" },
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-both-side-board/size-3x4" },
  ],
  "eco-premium-chalk-board": [
    { label: "1 × 1 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-1x1" },
    { label: "1 × 1.5 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-1x1.5" },
    { label: "1 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-1x2" },
    { label: "1.5 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-1.5x2" },
    { label: "1.5 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-1.5x3" },
    { label: "2 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-2x2" },
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-chalk-board/size-3x4" },
  ],
  "eco-premium-notice-board": [
    { label: "1.5 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/size-1.5x2" },
    { label: "1.5 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/size-1.5x3" },
    { label: "2 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/size-2x2" },
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-premium-notice-board/size-3x4" },
  ],
  "eco-regular-magnetic-board": [
    { label: "1 × 1 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-1x1" },
    { label: "1 × 1.5 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-1x1.5" },
    { label: "1 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-1x2" },
    { label: "1.5 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-1.5x2" },
    { label: "1.5 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-1.5x3" },
    { label: "2 × 2 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-2x2" },
    { label: "2 × 3 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-2x3" },
    { label: "2 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-2x4" },
    { label: "3 × 4 ft", image: "https://res.cloudinary.com/drt0rpkn2/image/upload/f_auto,q_auto/plusmark/products/eco-regular-magnetic-board/size-3x4" },
  ],
};
