/**
 * Board sizes with a photo per size. GENERATED by scripts/import-photos.mts — do not edit by hand.
 * Source: size folders in the Plusmark Drive (e.g. "2 X 3 WB - P-1").
 */
export interface SizeOption {
  label: string;
  image: string;
}

export const sizeOptions: Record<string, SizeOption[]> = {
  "metallic-premium-white-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-white-board/size-2x3.webp?v=d30f1a74bf" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-white-board/size-2x4.webp?v=e816c752f0" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-white-board/size-3x4.webp?v=fdf89fe05d" },
  ],
  "metallic-premium-chalk-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-chalk-board/size-2x3.webp?v=341ecee0a4" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-chalk-board/size-2x4.webp?v=b8159f563e" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-chalk-board/size-3x4.webp?v=5f1018ea3e" },
  ],
  "metallic-premium-notice-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-notice-board/size-2x3.webp?v=61f12483a7" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-notice-board/size-2x4.webp?v=8f74cf3bd4" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-notice-board/size-3x4.webp?v=e0d24594e2" },
  ],
  "metallic-premium-magnetic-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-magnetic-board/size-2x3.webp?v=de3ff017cb" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-magnetic-board/size-2x4.webp?v=c3c021e29e" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-magnetic-board/size-3x4.webp?v=f402705641" },
  ],
  "metallic-premium-ceramic-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-ceramic-board/size-2x3.webp?v=0b940ebe71" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-ceramic-board/size-2x4.webp?v=63da3ba0c9" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-ceramic-board/size-3x4.webp?v=f59942ffe7" },
  ],
  "eco-premium-white-board": [
    { label: "1 × 1 ft", image: "/images/products/eco-premium-white-board/size-1x1.webp?v=a88e937b65" },
    { label: "1 × 1.5 ft", image: "/images/products/eco-premium-white-board/size-1x1.5.webp?v=4d05e8d436" },
    { label: "1 × 2 ft", image: "/images/products/eco-premium-white-board/size-1x2.webp?v=7ce19dc847" },
    { label: "1.5 × 2 ft", image: "/images/products/eco-premium-white-board/size-1.5x2.webp?v=97c4568893" },
    { label: "1.5 × 3 ft", image: "/images/products/eco-premium-white-board/size-1.5x3.webp?v=d8d78cb6e0" },
    { label: "2 × 2 ft", image: "/images/products/eco-premium-white-board/size-2x2.webp?v=1eb05dbc4b" },
    { label: "2 × 3 ft", image: "/images/products/eco-premium-white-board/size-2x3.webp?v=bf05f92500" },
    { label: "2 × 4 ft", image: "/images/products/eco-premium-white-board/size-2x4.webp?v=82ff6a5983" },
    { label: "3 × 4 ft", image: "/images/products/eco-premium-white-board/size-3x4.webp?v=4ad934753b" },
  ],
  "eco-premium-chalk-board": [
    { label: "1 × 1 ft", image: "/images/products/eco-premium-chalk-board/size-1x1.webp?v=f6adabfa32" },
    { label: "1 × 1.5 ft", image: "/images/products/eco-premium-chalk-board/size-1x1.5.webp?v=2309ec28fc" },
    { label: "1 × 2 ft", image: "/images/products/eco-premium-chalk-board/size-1x2.webp?v=7c869daa73" },
    { label: "1.5 × 2 ft", image: "/images/products/eco-premium-chalk-board/size-1.5x2.webp?v=648ddc6ee1" },
    { label: "1.5 × 3 ft", image: "/images/products/eco-premium-chalk-board/size-1.5x3.webp?v=3ed3dd59e0" },
    { label: "2 × 2 ft", image: "/images/products/eco-premium-chalk-board/size-2x2.webp?v=0df592239d" },
    { label: "2 × 3 ft", image: "/images/products/eco-premium-chalk-board/size-2x3.webp?v=23b800bc20" },
    { label: "2 × 4 ft", image: "/images/products/eco-premium-chalk-board/size-2x4.webp?v=17112c8d7c" },
    { label: "3 × 4 ft", image: "/images/products/eco-premium-chalk-board/size-3x4.webp?v=8f4de38e9e" },
  ],
  "eco-premium-notice-board": [
    { label: "1.5 × 2 ft", image: "/images/products/eco-premium-notice-board/size-1.5x2.webp?v=3481f227a4" },
    { label: "1.5 × 3 ft", image: "/images/products/eco-premium-notice-board/size-1.5x3.webp?v=e566e782b3" },
    { label: "2 × 2 ft", image: "/images/products/eco-premium-notice-board/size-2x2.webp?v=926eedc99e" },
    { label: "2 × 3 ft", image: "/images/products/eco-premium-notice-board/size-2x3.webp?v=2f14777779" },
    { label: "2 × 4 ft", image: "/images/products/eco-premium-notice-board/size-2x4.webp?v=3a593699ac" },
    { label: "3 × 4 ft", image: "/images/products/eco-premium-notice-board/size-3x4.webp?v=05ee317e6b" },
  ],
};
