/**
 * Board sizes with a photo per size. GENERATED by scripts/import-photos.mts — do not edit by hand.
 * Source: per-size folders of the HQ listing photos (e.g. "ECO WB/2x3 Feet").
 */
export interface SizeOption {
  label: string;
  image: string;
}

export const sizeOptions: Record<string, SizeOption[]> = {
  "metallic-premium-white-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-white-board/size-2x3.webp?v=a3c71e8c3a" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-white-board/size-2x4.webp?v=77713a1bfa" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-white-board/size-3x4.webp?v=9b5fe90f63" },
  ],
  "metallic-premium-chalk-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-chalk-board/size-2x3.webp?v=0bdb41a5a0" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-chalk-board/size-2x4.webp?v=5d5aa62ec5" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-chalk-board/size-3x4.webp?v=8ae40e3e25" },
  ],
  "metallic-premium-notice-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-notice-board/size-2x3.webp?v=2580051b3a" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-notice-board/size-2x4.webp?v=0d6fa7162a" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-notice-board/size-3x4.webp?v=fae8344435" },
  ],
  "metallic-premium-magnetic-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-magnetic-board/size-2x3.webp?v=3ecdcbf72d" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-magnetic-board/size-2x4.webp?v=726c879ce9" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-magnetic-board/size-3x4.webp?v=16a892fcd0" },
  ],
  "metallic-premium-ceramic-board": [
    { label: "2 × 3 ft", image: "/images/products/metallic-premium-ceramic-board/size-2x3.webp?v=05639f1c8e" },
    { label: "2 × 4 ft", image: "/images/products/metallic-premium-ceramic-board/size-2x4.webp?v=eebb79d229" },
    { label: "3 × 4 ft", image: "/images/products/metallic-premium-ceramic-board/size-3x4.webp?v=75d5470fb0" },
  ],
  "eco-premium-white-board": [
    { label: "1 × 1 ft", image: "/images/products/eco-premium-white-board/size-1x1.webp?v=49477c4c8b" },
    { label: "1 × 1.5 ft", image: "/images/products/eco-premium-white-board/size-1x1.5.webp?v=4f6168b9a0" },
    { label: "1 × 2 ft", image: "/images/products/eco-premium-white-board/size-1x2.webp?v=081d673ded" },
    { label: "1.5 × 2 ft", image: "/images/products/eco-premium-white-board/size-1.5x2.webp?v=726ce56f94" },
    { label: "1.5 × 3 ft", image: "/images/products/eco-premium-white-board/size-1.5x3.webp?v=941120a25b" },
    { label: "2 × 2 ft", image: "/images/products/eco-premium-white-board/size-2x2.webp?v=42c7670e80" },
    { label: "2 × 3 ft", image: "/images/products/eco-premium-white-board/size-2x3.webp?v=47a56818c1" },
    { label: "2 × 4 ft", image: "/images/products/eco-premium-white-board/size-2x4.webp?v=88b7218216" },
    { label: "3 × 4 ft", image: "/images/products/eco-premium-white-board/size-3x4.webp?v=cb995a3c91" },
  ],
  "eco-premium-both-side-board": [
    { label: "1 × 1 ft", image: "/images/products/eco-premium-both-side-board/size-1x1.webp?v=cc470796d5" },
    { label: "1 × 1.5 ft", image: "/images/products/eco-premium-both-side-board/size-1x1.5.webp?v=2ac3d15a51" },
    { label: "1 × 2 ft", image: "/images/products/eco-premium-both-side-board/size-1x2.webp?v=cfb6df0344" },
    { label: "1.5 × 2 ft", image: "/images/products/eco-premium-both-side-board/size-1.5x2.webp?v=8c757eb92b" },
    { label: "1.5 × 3 ft", image: "/images/products/eco-premium-both-side-board/size-1.5x3.webp?v=360271e4d0" },
    { label: "2 × 2 ft", image: "/images/products/eco-premium-both-side-board/size-2x2.webp?v=5cf3b0c52e" },
    { label: "2 × 3 ft", image: "/images/products/eco-premium-both-side-board/size-2x3.webp?v=39dff3ded5" },
    { label: "2 × 4 ft", image: "/images/products/eco-premium-both-side-board/size-2x4.webp?v=6f71c5b96b" },
    { label: "3 × 4 ft", image: "/images/products/eco-premium-both-side-board/size-3x4.webp?v=429737223d" },
  ],
  "eco-premium-chalk-board": [
    { label: "1 × 1 ft", image: "/images/products/eco-premium-chalk-board/size-1x1.webp?v=fb5c65dc95" },
    { label: "1 × 1.5 ft", image: "/images/products/eco-premium-chalk-board/size-1x1.5.webp?v=c24b01b043" },
    { label: "1 × 2 ft", image: "/images/products/eco-premium-chalk-board/size-1x2.webp?v=ea2767762a" },
    { label: "1.5 × 2 ft", image: "/images/products/eco-premium-chalk-board/size-1.5x2.webp?v=50529b97dd" },
    { label: "1.5 × 3 ft", image: "/images/products/eco-premium-chalk-board/size-1.5x3.webp?v=b38f339a92" },
    { label: "2 × 2 ft", image: "/images/products/eco-premium-chalk-board/size-2x2.webp?v=8d6f48707c" },
    { label: "2 × 3 ft", image: "/images/products/eco-premium-chalk-board/size-2x3.webp?v=dba002df92" },
    { label: "2 × 4 ft", image: "/images/products/eco-premium-chalk-board/size-2x4.webp?v=37f600a91b" },
    { label: "3 × 4 ft", image: "/images/products/eco-premium-chalk-board/size-3x4.webp?v=dd08f29fd9" },
  ],
  "eco-premium-notice-board": [
    { label: "1.5 × 2 ft", image: "/images/products/eco-premium-notice-board/size-1.5x2.webp?v=a6c35b8981" },
    { label: "1.5 × 3 ft", image: "/images/products/eco-premium-notice-board/size-1.5x3.webp?v=ec8b5ae42a" },
    { label: "2 × 2 ft", image: "/images/products/eco-premium-notice-board/size-2x2.webp?v=7e62ef588a" },
    { label: "2 × 3 ft", image: "/images/products/eco-premium-notice-board/size-2x3.webp?v=7c83896bae" },
    { label: "2 × 4 ft", image: "/images/products/eco-premium-notice-board/size-2x4.webp?v=6ab77599a1" },
    { label: "3 × 4 ft", image: "/images/products/eco-premium-notice-board/size-3x4.webp?v=e659353c9b" },
  ],
  "eco-regular-magnetic-board": [
    { label: "1 × 1 ft", image: "/images/products/eco-regular-magnetic-board/size-1x1.webp?v=c10a116f60" },
    { label: "1 × 1.5 ft", image: "/images/products/eco-regular-magnetic-board/size-1x1.5.webp?v=200aaa60be" },
    { label: "1 × 2 ft", image: "/images/products/eco-regular-magnetic-board/size-1x2.webp?v=807bfa9224" },
    { label: "1.5 × 2 ft", image: "/images/products/eco-regular-magnetic-board/size-1.5x2.webp?v=88d6befffc" },
    { label: "1.5 × 3 ft", image: "/images/products/eco-regular-magnetic-board/size-1.5x3.webp?v=916f2df0e7" },
    { label: "2 × 2 ft", image: "/images/products/eco-regular-magnetic-board/size-2x2.webp?v=7ed1597b0a" },
    { label: "2 × 3 ft", image: "/images/products/eco-regular-magnetic-board/size-2x3.webp?v=15037b0795" },
    { label: "2 × 4 ft", image: "/images/products/eco-regular-magnetic-board/size-2x4.webp?v=72627dd86f" },
    { label: "3 × 4 ft", image: "/images/products/eco-regular-magnetic-board/size-3x4.webp?v=98f652a6b5" },
  ],
};
